### ISSUE TITLE
Paths are wrongly converted

### ISSUE THREAD

**Issue by XhmikosR** [webdoc/grunt-concat-css#2]
Hi. When using grunt-concat-css on Windows I end up with wrong slashes for URLs.

``` css
.sprite {
    background-image: url("../img/sprite.png");
    background-repeat: no-repeat;
}
```

``` css
.sprite {
    background-image: url('source\assets\img\sprite.png');
    background-repeat: no-repeat;
}
```

The same goes for font-face src etc.

My Gruntfile's relevant part:

``` js
        concat_css: {
            dist: {
                src: ["<%= dirs.src %>/assets/css/bootstrap.css",
                      "<%= dirs.src %>/assets/css/font-awesome.css",
                      "<%= dirs.src %>/assets/css/jquery.fancybox.css",
                      "<%= dirs.src %>/assets/css/jquery.fancybox-thumbs.css",
                      "<%= dirs.src %>/assets/css/style.css"],
                dest: "<%= dirs.dest %>/assets/css/pack.css"
            }
        },
```
